package com.payconiq.zekigu.githubrepos;

/**
 * Created by zekigu on 16.09.2017.
 */

public class SampleJSONRepoData {

    public static final String sampleRepoJSONObject = "{\n" +
            "\"id\": 3070104,\n" +
            "\"name\": \"abs.io\",\n" +
            "\"full_name\": \"JakeWharton/abs.io\",\n" +
            "\"owner\": {\n" +
            "\"login\": \"JakeWharton\",\n" +
            "\"id\": 66577,\n" +
            "\"avatar_url\": \"https://avatars0.githubusercontent.com/u/66577?v=4\",\n" +
            "\"gravatar_id\": \"\",\n" +
            "\"url\": \"https://api.github.com/users/JakeWharton\",\n" +
            "\"html_url\": \"https://github.com/JakeWharton\",\n" +
            "\"followers_url\": \"https://api.github.com/users/JakeWharton/followers\",\n" +
            "\"following_url\": \"https://api.github.com/users/JakeWharton/following{/other_user}\",\n" +
            "\"gists_url\": \"https://api.github.com/users/JakeWharton/gists{/gist_id}\",\n" +
            "\"starred_url\": \"https://api.github.com/users/JakeWharton/starred{/owner}{/repo}\",\n" +
            "\"subscriptions_url\": \"https://api.github.com/users/JakeWharton/subscriptions\",\n" +
            "\"organizations_url\": \"https://api.github.com/users/JakeWharton/orgs\",\n" +
            "\"repos_url\": \"https://api.github.com/users/JakeWharton/repos\",\n" +
            "\"events_url\": \"https://api.github.com/users/JakeWharton/events{/privacy}\",\n" +
            "\"received_events_url\": \"https://api.github.com/users/JakeWharton/received_events\",\n" +
            "\"type\": \"User\",\n" +
            "\"site_admin\": false\n" +
            "},\n" +
            "\"private\": false,\n" +
            "\"html_url\": \"https://github.com/JakeWharton/abs.io\",\n" +
            "\"description\": \"Simple URL shortener for ActionBarSherlock using node.js and express.\",\n" +
            "\"fork\": false,\n" +
            "\"url\": \"https://api.github.com/repos/JakeWharton/abs.io\",\n" +
            "\"forks_url\": \"https://api.github.com/repos/JakeWharton/abs.io/forks\",\n" +
            "\"keys_url\": \"https://api.github.com/repos/JakeWharton/abs.io/keys{/key_id}\",\n" +
            "\"collaborators_url\": \"https://api.github.com/repos/JakeWharton/abs.io/collaborators{/collaborator}\",\n" +
            "\"teams_url\": \"https://api.github.com/repos/JakeWharton/abs.io/teams\",\n" +
            "\"hooks_url\": \"https://api.github.com/repos/JakeWharton/abs.io/hooks\",\n" +
            "\"issue_events_url\": \"https://api.github.com/repos/JakeWharton/abs.io/issues/events{/number}\",\n" +
            "\"events_url\": \"https://api.github.com/repos/JakeWharton/abs.io/events\",\n" +
            "\"assignees_url\": \"https://api.github.com/repos/JakeWharton/abs.io/assignees{/user}\",\n" +
            "\"branches_url\": \"https://api.github.com/repos/JakeWharton/abs.io/branches{/branch}\",\n" +
            "\"tags_url\": \"https://api.github.com/repos/JakeWharton/abs.io/tags\",\n" +
            "\"blobs_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/blobs{/sha}\",\n" +
            "\"git_tags_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/tags{/sha}\",\n" +
            "\"git_refs_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/refs{/sha}\",\n" +
            "\"trees_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/trees{/sha}\",\n" +
            "\"statuses_url\": \"https://api.github.com/repos/JakeWharton/abs.io/statuses/{sha}\",\n" +
            "\"languages_url\": \"https://api.github.com/repos/JakeWharton/abs.io/languages\",\n" +
            "\"stargazers_url\": \"https://api.github.com/repos/JakeWharton/abs.io/stargazers\",\n" +
            "\"contributors_url\": \"https://api.github.com/repos/JakeWharton/abs.io/contributors\",\n" +
            "\"subscribers_url\": \"https://api.github.com/repos/JakeWharton/abs.io/subscribers\",\n" +
            "\"subscription_url\": \"https://api.github.com/repos/JakeWharton/abs.io/subscription\",\n" +
            "\"commits_url\": \"https://api.github.com/repos/JakeWharton/abs.io/commits{/sha}\",\n" +
            "\"git_commits_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/commits{/sha}\",\n" +
            "\"comments_url\": \"https://api.github.com/repos/JakeWharton/abs.io/comments{/number}\",\n" +
            "\"issue_comment_url\": \"https://api.github.com/repos/JakeWharton/abs.io/issues/comments{/number}\",\n" +
            "\"contents_url\": \"https://api.github.com/repos/JakeWharton/abs.io/contents/{+path}\",\n" +
            "\"compare_url\": \"https://api.github.com/repos/JakeWharton/abs.io/compare/{base}...{head}\",\n" +
            "\"merges_url\": \"https://api.github.com/repos/JakeWharton/abs.io/merges\",\n" +
            "\"archive_url\": \"https://api.github.com/repos/JakeWharton/abs.io/{archive_format}{/ref}\",\n" +
            "\"downloads_url\": \"https://api.github.com/repos/JakeWharton/abs.io/downloads\",\n" +
            "\"issues_url\": \"https://api.github.com/repos/JakeWharton/abs.io/issues{/number}\",\n" +
            "\"pulls_url\": \"https://api.github.com/repos/JakeWharton/abs.io/pulls{/number}\",\n" +
            "\"milestones_url\": \"https://api.github.com/repos/JakeWharton/abs.io/milestones{/number}\",\n" +
            "\"notifications_url\": \"https://api.github.com/repos/JakeWharton/abs.io/notifications{?since,all,participating}\",\n" +
            "\"labels_url\": \"https://api.github.com/repos/JakeWharton/abs.io/labels{/name}\",\n" +
            "\"releases_url\": \"https://api.github.com/repos/JakeWharton/abs.io/releases{/id}\",\n" +
            "\"deployments_url\": \"https://api.github.com/repos/JakeWharton/abs.io/deployments\",\n" +
            "\"created_at\": \"2011-12-29T18:02:34Z\",\n" +
            "\"updated_at\": \"2017-08-09T14:39:21Z\",\n" +
            "\"pushed_at\": \"2011-12-29T18:02:44Z\",\n" +
            "\"git_url\": \"git://github.com/JakeWharton/abs.io.git\",\n" +
            "\"ssh_url\": \"git@github.com:JakeWharton/abs.io.git\",\n" +
            "\"clone_url\": \"https://github.com/JakeWharton/abs.io.git\",\n" +
            "\"svn_url\": \"https://github.com/JakeWharton/abs.io\",\n" +
            "\"homepage\": \"http://abs.io\",\n" +
            "\"size\": 108,\n" +
            "\"stargazers_count\": 6,\n" +
            "\"watchers_count\": 6,\n" +
            "\"language\": \"JavaScript\",\n" +
            "\"has_issues\": true,\n" +
            "\"has_projects\": true,\n" +
            "\"has_downloads\": true,\n" +
            "\"has_wiki\": false,\n" +
            "\"has_pages\": false,\n" +
            "\"forks_count\": 1,\n" +
            "\"mirror_url\": null,\n" +
            "\"open_issues_count\": 0,\n" +
            "\"forks\": 1,\n" +
            "\"open_issues\": 0,\n" +
            "\"watchers\": 6,\n" +
            "\"default_branch\": \"master\"\n" +
            "}";

    public static final String sampleReposJSONArray = "[" +
            "{"
            +
            "\t\t\"id\": 3070104,\n" +
            "\t\t\"name\": \"abs.io\",\n" +
            "\t\t\"full_name\": \"JakeWharton/abs.io\",\n" +
            "\t\t\"owner\": {\n" +
            "\t\t\t\"login\": \"JakeWharton\",\n" +
            "\t\t\t\"id\": 66577,\n" +
            "\t\t\t\"avatar_url\": \"https://avatars0.githubusercontent.com/u/66577?v=4\",\n" +
            "\t\t\t\"gravatar_id\": \"\",\n" +
            "\t\t\t\"url\": \"https://api.github.com/users/JakeWharton\",\n" +
            "\t\t\t\"html_url\": \"https://github.com/JakeWharton\",\n" +
            "\t\t\t\"followers_url\": \"https://api.github.com/users/JakeWharton/followers\",\n" +
            "\t\t\t\"following_url\": \"https://api.github.com/users/JakeWharton/following{/other_user}\",\n" +
            "\t\t\t\"gists_url\": \"https://api.github.com/users/JakeWharton/gists{/gist_id}\",\n" +
            "\t\t\t\"starred_url\": \"https://api.github.com/users/JakeWharton/starred{/owner}{/repo}\",\n" +
            "\t\t\t\"subscriptions_url\": \"https://api.github.com/users/JakeWharton/subscriptions\",\n" +
            "\t\t\t\"organizations_url\": \"https://api.github.com/users/JakeWharton/orgs\",\n" +
            "\t\t\t\"repos_url\": \"https://api.github.com/users/JakeWharton/repos\",\n" +
            "\t\t\t\"events_url\": \"https://api.github.com/users/JakeWharton/events{/privacy}\",\n" +
            "\t\t\t\"received_events_url\": \"https://api.github.com/users/JakeWharton/received_events\",\n" +
            "\t\t\t\"type\": \"User\",\n" +
            "\t\t\t\"site_admin\": false\n" +
            "\t\t},\n" +
            "\t\t\"private\": false,\n" +
            "\t\t\"html_url\": \"https://github.com/JakeWharton/abs.io\",\n" +
            "\t\t\"description\": \"Simple URL shortener for ActionBarSherlock using node.js and express.\",\n" +
            "\t\t\"fork\": false,\n" +
            "\t\t\"url\": \"https://api.github.com/repos/JakeWharton/abs.io\",\n" +
            "\t\t\"forks_url\": \"https://api.github.com/repos/JakeWharton/abs.io/forks\",\n" +
            "\t\t\"keys_url\": \"https://api.github.com/repos/JakeWharton/abs.io/keys{/key_id}\",\n" +
            "\t\t\"collaborators_url\": \"https://api.github.com/repos/JakeWharton/abs.io/collaborators{/collaborator}\",\n" +
            "\t\t\"teams_url\": \"https://api.github.com/repos/JakeWharton/abs.io/teams\",\n" +
            "\t\t\"hooks_url\": \"https://api.github.com/repos/JakeWharton/abs.io/hooks\",\n" +
            "\t\t\"issue_events_url\": \"https://api.github.com/repos/JakeWharton/abs.io/issues/events{/number}\",\n" +
            "\t\t\"events_url\": \"https://api.github.com/repos/JakeWharton/abs.io/events\",\n" +
            "\t\t\"assignees_url\": \"https://api.github.com/repos/JakeWharton/abs.io/assignees{/user}\",\n" +
            "\t\t\"branches_url\": \"https://api.github.com/repos/JakeWharton/abs.io/branches{/branch}\",\n" +
            "\t\t\"tags_url\": \"https://api.github.com/repos/JakeWharton/abs.io/tags\",\n" +
            "\t\t\"blobs_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/blobs{/sha}\",\n" +
            "\t\t\"git_tags_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/tags{/sha}\",\n" +
            "\t\t\"git_refs_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/refs{/sha}\",\n" +
            "\t\t\"trees_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/trees{/sha}\",\n" +
            "\t\t\"statuses_url\": \"https://api.github.com/repos/JakeWharton/abs.io/statuses/{sha}\",\n" +
            "\t\t\"languages_url\": \"https://api.github.com/repos/JakeWharton/abs.io/languages\",\n" +
            "\t\t\"stargazers_url\": \"https://api.github.com/repos/JakeWharton/abs.io/stargazers\",\n" +
            "\t\t\"contributors_url\": \"https://api.github.com/repos/JakeWharton/abs.io/contributors\",\n" +
            "\t\t\"subscribers_url\": \"https://api.github.com/repos/JakeWharton/abs.io/subscribers\",\n" +
            "\t\t\"subscription_url\": \"https://api.github.com/repos/JakeWharton/abs.io/subscription\",\n" +
            "\t\t\"commits_url\": \"https://api.github.com/repos/JakeWharton/abs.io/commits{/sha}\",\n" +
            "\t\t\"git_commits_url\": \"https://api.github.com/repos/JakeWharton/abs.io/git/commits{/sha}\",\n" +
            "\t\t\"comments_url\": \"https://api.github.com/repos/JakeWharton/abs.io/comments{/number}\",\n" +
            "\t\t\"issue_comment_url\": \"https://api.github.com/repos/JakeWharton/abs.io/issues/comments{/number}\",\n" +
            "\t\t\"contents_url\": \"https://api.github.com/repos/JakeWharton/abs.io/contents/{+path}\",\n" +
            "\t\t\"compare_url\": \"https://api.github.com/repos/JakeWharton/abs.io/compare/{base}...{head}\",\n" +
            "\t\t\"merges_url\": \"https://api.github.com/repos/JakeWharton/abs.io/merges\",\n" +
            "\t\t\"archive_url\": \"https://api.github.com/repos/JakeWharton/abs.io/{archive_format}{/ref}\",\n" +
            "\t\t\"downloads_url\": \"https://api.github.com/repos/JakeWharton/abs.io/downloads\",\n" +
            "\t\t\"issues_url\": \"https://api.github.com/repos/JakeWharton/abs.io/issues{/number}\",\n" +
            "\t\t\"pulls_url\": \"https://api.github.com/repos/JakeWharton/abs.io/pulls{/number}\",\n" +
            "\t\t\"milestones_url\": \"https://api.github.com/repos/JakeWharton/abs.io/milestones{/number}\",\n" +
            "\t\t\"notifications_url\": \"https://api.github.com/repos/JakeWharton/abs.io/notifications{?since,all,participating}\",\n" +
            "\t\t\"labels_url\": \"https://api.github.com/repos/JakeWharton/abs.io/labels{/name}\",\n" +
            "\t\t\"releases_url\": \"https://api.github.com/repos/JakeWharton/abs.io/releases{/id}\",\n" +
            "\t\t\"deployments_url\": \"https://api.github.com/repos/JakeWharton/abs.io/deployments\",\n" +
            "\t\t\"created_at\": \"2011-12-29T18:02:34Z\",\n" +
            "\t\t\"updated_at\": \"2017-08-09T14:39:21Z\",\n" +
            "\t\t\"pushed_at\": \"2011-12-29T18:02:44Z\",\n" +
            "\t\t\"git_url\": \"git://github.com/JakeWharton/abs.io.git\",\n" +
            "\t\t\"ssh_url\": \"git@github.com:JakeWharton/abs.io.git\",\n" +
            "\t\t\"clone_url\": \"https://github.com/JakeWharton/abs.io.git\",\n" +
            "\t\t\"svn_url\": \"https://github.com/JakeWharton/abs.io\",\n" +
            "\t\t\"homepage\": \"http://abs.io\",\n" +
            "\t\t\"size\": 108,\n" +
            "\t\t\"stargazers_count\": 6,\n" +
            "\t\t\"watchers_count\": 6,\n" +
            "\t\t\"language\": \"JavaScript\",\n" +
            "\t\t\"has_issues\": true,\n" +
            "\t\t\"has_projects\": true,\n" +
            "\t\t\"has_downloads\": true,\n" +
            "\t\t\"has_wiki\": false,\n" +
            "\t\t\"has_pages\": false,\n" +
            "\t\t\"forks_count\": 1,\n" +
            "\t\t\"mirror_url\": null,\n" +
            "\t\t\"open_issues_count\": 0,\n" +
            "\t\t\"forks\": 1,\n" +
            "\t\t\"open_issues\": 0,\n" +
            "\t\t\"watchers\": 6,\n" +
            "\t\t\"default_branch\": \"master\"\n" +
            "\t},\n" +
            "\t{\n" +
            "\t\t\"id\": 1451060,\n" +
            "\t\t\"name\": \"ActionBarSherlock\",\n" +
            "\t\t\"full_name\": \"JakeWharton/ActionBarSherlock\",\n" +
            "\t\t\"owner\": {\n" +
            "\t\t\t\"login\": \"JakeWharton\",\n" +
            "\t\t\t\"id\": 66577,\n" +
            "\t\t\t\"avatar_url\": \"https://avatars0.githubusercontent.com/u/66577?v=4\",\n" +
            "\t\t\t\"gravatar_id\": \"\",\n" +
            "\t\t\t\"url\": \"https://api.github.com/users/JakeWharton\",\n" +
            "\t\t\t\"html_url\": \"https://github.com/JakeWharton\",\n" +
            "\t\t\t\"followers_url\": \"https://api.github.com/users/JakeWharton/followers\",\n" +
            "\t\t\t\"following_url\": \"https://api.github.com/users/JakeWharton/following{/other_user}\",\n" +
            "\t\t\t\"gists_url\": \"https://api.github.com/users/JakeWharton/gists{/gist_id}\",\n" +
            "\t\t\t\"starred_url\": \"https://api.github.com/users/JakeWharton/starred{/owner}{/repo}\",\n" +
            "\t\t\t\"subscriptions_url\": \"https://api.github.com/users/JakeWharton/subscriptions\",\n" +
            "\t\t\t\"organizations_url\": \"https://api.github.com/users/JakeWharton/orgs\",\n" +
            "\t\t\t\"repos_url\": \"https://api.github.com/users/JakeWharton/repos\",\n" +
            "\t\t\t\"events_url\": \"https://api.github.com/users/JakeWharton/events{/privacy}\",\n" +
            "\t\t\t\"received_events_url\": \"https://api.github.com/users/JakeWharton/received_events\",\n" +
            "\t\t\t\"type\": \"User\",\n" +
            "\t\t\t\"site_admin\": false\n" +
            "\t\t},\n" +
            "\t\t\"private\": false,\n" +
            "\t\t\"html_url\": \"https://github.com/JakeWharton/ActionBarSherlock\",\n" +
            "\t\t\"description\": \"[DEPRECATED] Action bar implementation which uses the native action bar on Android 4.0+ and a custom implementation on pre-4.0 through a single API and theme.\",\n" +
            "\t\t\"fork\": false,\n" +
            "\t\t\"url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock\",\n" +
            "\t\t\"forks_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/forks\",\n" +
            "\t\t\"keys_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/keys{/key_id}\",\n" +
            "\t\t\"collaborators_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/collaborators{/collaborator}\",\n" +
            "\t\t\"teams_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/teams\",\n" +
            "\t\t\"hooks_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/hooks\",\n" +
            "\t\t\"issue_events_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/issues/events{/number}\",\n" +
            "\t\t\"events_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/events\",\n" +
            "\t\t\"assignees_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/assignees{/user}\",\n" +
            "\t\t\"branches_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/branches{/branch}\",\n" +
            "\t\t\"tags_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/tags\",\n" +
            "\t\t\"blobs_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/git/blobs{/sha}\",\n" +
            "\t\t\"git_tags_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/git/tags{/sha}\",\n" +
            "\t\t\"git_refs_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/git/refs{/sha}\",\n" +
            "\t\t\"trees_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/git/trees{/sha}\",\n" +
            "\t\t\"statuses_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/statuses/{sha}\",\n" +
            "\t\t\"languages_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/languages\",\n" +
            "\t\t\"stargazers_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/stargazers\",\n" +
            "\t\t\"contributors_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/contributors\",\n" +
            "\t\t\"subscribers_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/subscribers\",\n" +
            "\t\t\"subscription_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/subscription\",\n" +
            "\t\t\"commits_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/commits{/sha}\",\n" +
            "\t\t\"git_commits_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/git/commits{/sha}\",\n" +
            "\t\t\"comments_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/comments{/number}\",\n" +
            "\t\t\"issue_comment_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/issues/comments{/number}\",\n" +
            "\t\t\"contents_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/contents/{+path}\",\n" +
            "\t\t\"compare_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/compare/{base}...{head}\",\n" +
            "\t\t\"merges_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/merges\",\n" +
            "\t\t\"archive_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/{archive_format}{/ref}\",\n" +
            "\t\t\"downloads_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/downloads\",\n" +
            "\t\t\"issues_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/issues{/number}\",\n" +
            "\t\t\"pulls_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/pulls{/number}\",\n" +
            "\t\t\"milestones_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/milestones{/number}\",\n" +
            "\t\t\"notifications_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/notifications{?since,all,participating}\",\n" +
            "\t\t\"labels_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/labels{/name}\",\n" +
            "\t\t\"releases_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/releases{/id}\",\n" +
            "\t\t\"deployments_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock/deployments\",\n" +
            "\t\t\"created_at\": \"2011-03-07T17:28:54Z\",\n" +
            "\t\t\"updated_at\": \"2017-09-16T12:29:59Z\",\n" +
            "\t\t\"pushed_at\": \"2015-12-17T17:54:50Z\",\n" +
            "\t\t\"git_url\": \"git://github.com/JakeWharton/ActionBarSherlock.git\",\n" +
            "\t\t\"ssh_url\": \"git@github.com:JakeWharton/ActionBarSherlock.git\",\n" +
            "\t\t\"clone_url\": \"https://github.com/JakeWharton/ActionBarSherlock.git\",\n" +
            "\t\t\"svn_url\": \"https://github.com/JakeWharton/ActionBarSherlock\",\n" +
            "\t\t\"homepage\": \"http://actionbarsherlock.com\",\n" +
            "\t\t\"size\": 21244,\n" +
            "\t\t\"stargazers_count\": 7357,\n" +
            "\t\t\"watchers_count\": 7357,\n" +
            "\t\t\"language\": \"Java\",\n" +
            "\t\t\"has_issues\": true,\n" +
            "\t\t\"has_projects\": true,\n" +
            "\t\t\"has_downloads\": true,\n" +
            "\t\t\"has_wiki\": false,\n" +
            "\t\t\"has_pages\": true,\n" +
            "\t\t\"forks_count\": 4031,\n" +
            "\t\t\"mirror_url\": null,\n" +
            "\t\t\"open_issues_count\": 92,\n" +
            "\t\t\"forks\": 4031,\n" +
            "\t\t\"open_issues\": 92,\n" +
            "\t\t\"watchers\": 7357,\n" +
            "\t\t\"default_branch\": \"master\"\n" +
            "\t},\n" +
            "\t{\n" +
            "\t\t\"id\": 11718829,\n" +
            "\t\t\"name\": \"ActionBarSherlock-Gradle-Sample\",\n" +
            "\t\t\"full_name\": \"JakeWharton/ActionBarSherlock-Gradle-Sample\",\n" +
            "\t\t\"owner\": {\n" +
            "\t\t\t\"login\": \"JakeWharton\",\n" +
            "\t\t\t\"id\": 66577,\n" +
            "\t\t\t\"avatar_url\": \"https://avatars0.githubusercontent.com/u/66577?v=4\",\n" +
            "\t\t\t\"gravatar_id\": \"\",\n" +
            "\t\t\t\"url\": \"https://api.github.com/users/JakeWharton\",\n" +
            "\t\t\t\"html_url\": \"https://github.com/JakeWharton\",\n" +
            "\t\t\t\"followers_url\": \"https://api.github.com/users/JakeWharton/followers\",\n" +
            "\t\t\t\"following_url\": \"https://api.github.com/users/JakeWharton/following{/other_user}\",\n" +
            "\t\t\t\"gists_url\": \"https://api.github.com/users/JakeWharton/gists{/gist_id}\",\n" +
            "\t\t\t\"starred_url\": \"https://api.github.com/users/JakeWharton/starred{/owner}{/repo}\",\n" +
            "\t\t\t\"subscriptions_url\": \"https://api.github.com/users/JakeWharton/subscriptions\",\n" +
            "\t\t\t\"organizations_url\": \"https://api.github.com/users/JakeWharton/orgs\",\n" +
            "\t\t\t\"repos_url\": \"https://api.github.com/users/JakeWharton/repos\",\n" +
            "\t\t\t\"events_url\": \"https://api.github.com/users/JakeWharton/events{/privacy}\",\n" +
            "\t\t\t\"received_events_url\": \"https://api.github.com/users/JakeWharton/received_events\",\n" +
            "\t\t\t\"type\": \"User\",\n" +
            "\t\t\t\"site_admin\": false\n" +
            "\t\t},\n" +
            "\t\t\"private\": false,\n" +
            "\t\t\"html_url\": \"https://github.com/JakeWharton/ActionBarSherlock-Gradle-Sample\",\n" +
            "\t\t\"description\": \"[DEPRECATED] A tiny sample project that uses ActionBarSherlock via Gradle\",\n" +
            "\t\t\"fork\": false,\n" +
            "\t\t\"url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample\",\n" +
            "\t\t\"forks_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/forks\",\n" +
            "\t\t\"keys_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/keys{/key_id}\",\n" +
            "\t\t\"collaborators_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/collaborators{/collaborator}\",\n" +
            "\t\t\"teams_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/teams\",\n" +
            "\t\t\"hooks_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/hooks\",\n" +
            "\t\t\"issue_events_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/issues/events{/number}\",\n" +
            "\t\t\"events_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/events\",\n" +
            "\t\t\"assignees_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/assignees{/user}\",\n" +
            "\t\t\"branches_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/branches{/branch}\",\n" +
            "\t\t\"tags_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/tags\",\n" +
            "\t\t\"blobs_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/git/blobs{/sha}\",\n" +
            "\t\t\"git_tags_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/git/tags{/sha}\",\n" +
            "\t\t\"git_refs_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/git/refs{/sha}\",\n" +
            "\t\t\"trees_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/git/trees{/sha}\",\n" +
            "\t\t\"statuses_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/statuses/{sha}\",\n" +
            "\t\t\"languages_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/languages\",\n" +
            "\t\t\"stargazers_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/stargazers\",\n" +
            "\t\t\"contributors_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/contributors\",\n" +
            "\t\t\"subscribers_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/subscribers\",\n" +
            "\t\t\"subscription_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/subscription\",\n" +
            "\t\t\"commits_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/commits{/sha}\",\n" +
            "\t\t\"git_commits_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/git/commits{/sha}\",\n" +
            "\t\t\"comments_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/comments{/number}\",\n" +
            "\t\t\"issue_comment_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/issues/comments{/number}\",\n" +
            "\t\t\"contents_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/contents/{+path}\",\n" +
            "\t\t\"compare_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/compare/{base}...{head}\",\n" +
            "\t\t\"merges_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/merges\",\n" +
            "\t\t\"archive_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/{archive_format}{/ref}\",\n" +
            "\t\t\"downloads_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/downloads\",\n" +
            "\t\t\"issues_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/issues{/number}\",\n" +
            "\t\t\"pulls_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/pulls{/number}\",\n" +
            "\t\t\"milestones_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/milestones{/number}\",\n" +
            "\t\t\"notifications_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/notifications{?since,all,participating}\",\n" +
            "\t\t\"labels_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/labels{/name}\",\n" +
            "\t\t\"releases_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/releases{/id}\",\n" +
            "\t\t\"deployments_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Gradle-Sample/deployments\",\n" +
            "\t\t\"created_at\": \"2013-07-28T11:19:58Z\",\n" +
            "\t\t\"updated_at\": \"2016-10-12T01:30:07Z\",\n" +
            "\t\t\"pushed_at\": \"2013-07-28T11:21:04Z\",\n" +
            "\t\t\"git_url\": \"git://github.com/JakeWharton/ActionBarSherlock-Gradle-Sample.git\",\n" +
            "\t\t\"ssh_url\": \"git@github.com:JakeWharton/ActionBarSherlock-Gradle-Sample.git\",\n" +
            "\t\t\"clone_url\": \"https://github.com/JakeWharton/ActionBarSherlock-Gradle-Sample.git\",\n" +
            "\t\t\"svn_url\": \"https://github.com/JakeWharton/ActionBarSherlock-Gradle-Sample\",\n" +
            "\t\t\"homepage\": \"\",\n" +
            "\t\t\"size\": 42,\n" +
            "\t\t\"stargazers_count\": 53,\n" +
            "\t\t\"watchers_count\": 53,\n" +
            "\t\t\"language\": \"Groovy\",\n" +
            "\t\t\"has_issues\": true,\n" +
            "\t\t\"has_projects\": true,\n" +
            "\t\t\"has_downloads\": true,\n" +
            "\t\t\"has_wiki\": false,\n" +
            "\t\t\"has_pages\": false,\n" +
            "\t\t\"forks_count\": 15,\n" +
            "\t\t\"mirror_url\": null,\n" +
            "\t\t\"open_issues_count\": 1,\n" +
            "\t\t\"forks\": 15,\n" +
            "\t\t\"open_issues\": 1,\n" +
            "\t\t\"watchers\": 53,\n" +
            "\t\t\"default_branch\": \"master\"\n" +
            "\t},\n" +
            "\t{\n" +
            "\t\t\"id\": 3473126,\n" +
            "\t\t\"name\": \"ActionBarSherlock-Plugin-Maps\",\n" +
            "\t\t\"full_name\": \"JakeWharton/ActionBarSherlock-Plugin-Maps\",\n" +
            "\t\t\"owner\": {\n" +
            "\t\t\t\"login\": \"JakeWharton\",\n" +
            "\t\t\t\"id\": 66577,\n" +
            "\t\t\t\"avatar_url\": \"https://avatars0.githubusercontent.com/u/66577?v=4\",\n" +
            "\t\t\t\"gravatar_id\": \"\",\n" +
            "\t\t\t\"url\": \"https://api.github.com/users/JakeWharton\",\n" +
            "\t\t\t\"html_url\": \"https://github.com/JakeWharton\",\n" +
            "\t\t\t\"followers_url\": \"https://api.github.com/users/JakeWharton/followers\",\n" +
            "\t\t\t\"following_url\": \"https://api.github.com/users/JakeWharton/following{/other_user}\",\n" +
            "\t\t\t\"gists_url\": \"https://api.github.com/users/JakeWharton/gists{/gist_id}\",\n" +
            "\t\t\t\"starred_url\": \"https://api.github.com/users/JakeWharton/starred{/owner}{/repo}\",\n" +
            "\t\t\t\"subscriptions_url\": \"https://api.github.com/users/JakeWharton/subscriptions\",\n" +
            "\t\t\t\"organizations_url\": \"https://api.github.com/users/JakeWharton/orgs\",\n" +
            "\t\t\t\"repos_url\": \"https://api.github.com/users/JakeWharton/repos\",\n" +
            "\t\t\t\"events_url\": \"https://api.github.com/users/JakeWharton/events{/privacy}\",\n" +
            "\t\t\t\"received_events_url\": \"https://api.github.com/users/JakeWharton/received_events\",\n" +
            "\t\t\t\"type\": \"User\",\n" +
            "\t\t\t\"site_admin\": false\n" +
            "\t\t},\n" +
            "\t\t\"private\": false,\n" +
            "\t\t\"html_url\": \"https://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps\",\n" +
            "\t\t\"description\": \"[DEPRECATED] Plugin for ActionBarSherlock which provides a base activity that can be used for adding a MapView to your action bar-enabled layouts.\",\n" +
            "\t\t\"fork\": false,\n" +
            "\t\t\"url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps\",\n" +
            "\t\t\"forks_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/forks\",\n" +
            "\t\t\"keys_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/keys{/key_id}\",\n" +
            "\t\t\"collaborators_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/collaborators{/collaborator}\",\n" +
            "\t\t\"teams_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/teams\",\n" +
            "\t\t\"hooks_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/hooks\",\n" +
            "\t\t\"issue_events_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/issues/events{/number}\",\n" +
            "\t\t\"events_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/events\",\n" +
            "\t\t\"assignees_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/assignees{/user}\",\n" +
            "\t\t\"branches_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/branches{/branch}\",\n" +
            "\t\t\"tags_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/tags\",\n" +
            "\t\t\"blobs_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/git/blobs{/sha}\",\n" +
            "\t\t\"git_tags_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/git/tags{/sha}\",\n" +
            "\t\t\"git_refs_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/git/refs{/sha}\",\n" +
            "\t\t\"trees_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/git/trees{/sha}\",\n" +
            "\t\t\"statuses_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/statuses/{sha}\",\n" +
            "\t\t\"languages_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/languages\",\n" +
            "\t\t\"stargazers_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/stargazers\",\n" +
            "\t\t\"contributors_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/contributors\",\n" +
            "\t\t\"subscribers_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/subscribers\",\n" +
            "\t\t\"subscription_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/subscription\",\n" +
            "\t\t\"commits_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/commits{/sha}\",\n" +
            "\t\t\"git_commits_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/git/commits{/sha}\",\n" +
            "\t\t\"comments_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/comments{/number}\",\n" +
            "\t\t\"issue_comment_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/issues/comments{/number}\",\n" +
            "\t\t\"contents_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/contents/{+path}\",\n" +
            "\t\t\"compare_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/compare/{base}...{head}\",\n" +
            "\t\t\"merges_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/merges\",\n" +
            "\t\t\"archive_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/{archive_format}{/ref}\",\n" +
            "\t\t\"downloads_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/downloads\",\n" +
            "\t\t\"issues_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/issues{/number}\",\n" +
            "\t\t\"pulls_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/pulls{/number}\",\n" +
            "\t\t\"milestones_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/milestones{/number}\",\n" +
            "\t\t\"notifications_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/notifications{?since,all,participating}\",\n" +
            "\t\t\"labels_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/labels{/name}\",\n" +
            "\t\t\"releases_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/releases{/id}\",\n" +
            "\t\t\"deployments_url\": \"https://api.github.com/repos/JakeWharton/ActionBarSherlock-Plugin-Maps/deployments\",\n" +
            "\t\t\"created_at\": \"2012-02-17T19:31:35Z\",\n" +
            "\t\t\"updated_at\": \"2017-02-27T10:25:15Z\",\n" +
            "\t\t\"pushed_at\": \"2013-06-06T04:59:56Z\",\n" +
            "\t\t\"git_url\": \"git://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps.git\",\n" +
            "\t\t\"ssh_url\": \"git@github.com:JakeWharton/ActionBarSherlock-Plugin-Maps.git\",\n" +
            "\t\t\"clone_url\": \"https://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps.git\",\n" +
            "\t\t\"svn_url\": \"https://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps\",\n" +
            "\t\t\"homepage\": \"http://actionbarsherlock.com\",\n" +
            "\t\t\"size\": 279,\n" +
            "\t\t\"stargazers_count\": 94,\n" +
            "\t\t\"watchers_count\": 94,\n" +
            "\t\t\"language\": \"Java\",\n" +
            "\t\t\"has_issues\": false,\n" +
            "\t\t\"has_projects\": true,\n" +
            "\t\t\"has_downloads\": true,\n" +
            "\t\t\"has_wiki\": false,\n" +
            "\t\t\"has_pages\": false,\n" +
            "\t\t\"forks_count\": 43,\n" +
            "\t\t\"mirror_url\": null,\n" +
            "\t\t\"open_issues_count\": 0,\n" +
            "\t\t\"forks\": 43,\n" +
            "\t\t\"open_issues\": 0,\n" +
            "\t\t\"watchers\": 94,\n" +
            "\t\t\"default_branch\": \"master\"\n" +
            "\t},\n" +
            "\t{\n" +
            "\t\t\"id\": 4930384,\n" +
            "\t\t\"name\": \"ActivityCompat2\",\n" +
            "\t\t\"full_name\": \"JakeWharton/ActivityCompat2\",\n" +
            "\t\t\"owner\": {\n" +
            "\t\t\t\"login\": \"JakeWharton\",\n" +
            "\t\t\t\"id\": 66577,\n" +
            "\t\t\t\"avatar_url\": \"https://avatars0.githubusercontent.com/u/66577?v=4\",\n" +
            "\t\t\t\"gravatar_id\": \"\",\n" +
            "\t\t\t\"url\": \"https://api.github.com/users/JakeWharton\",\n" +
            "\t\t\t\"html_url\": \"https://github.com/JakeWharton\",\n" +
            "\t\t\t\"followers_url\": \"https://api.github.com/users/JakeWharton/followers\",\n" +
            "\t\t\t\"following_url\": \"https://api.github.com/users/JakeWharton/following{/other_user}\",\n" +
            "\t\t\t\"gists_url\": \"https://api.github.com/users/JakeWharton/gists{/gist_id}\",\n" +
            "\t\t\t\"starred_url\": \"https://api.github.com/users/JakeWharton/starred{/owner}{/repo}\",\n" +
            "\t\t\t\"subscriptions_url\": \"https://api.github.com/users/JakeWharton/subscriptions\",\n" +
            "\t\t\t\"organizations_url\": \"https://api.github.com/users/JakeWharton/orgs\",\n" +
            "\t\t\t\"repos_url\": \"https://api.github.com/users/JakeWharton/repos\",\n" +
            "\t\t\t\"events_url\": \"https://api.github.com/users/JakeWharton/events{/privacy}\",\n" +
            "\t\t\t\"received_events_url\": \"https://api.github.com/users/JakeWharton/received_events\",\n" +
            "\t\t\t\"type\": \"User\",\n" +
            "\t\t\t\"site_admin\": false\n" +
            "\t\t},\n" +
            "\t\t\"private\": false,\n" +
            "\t\t\"html_url\": \"https://github.com/JakeWharton/ActivityCompat2\",\n" +
            "\t\t\"description\": \"[DEPRECATED] Please use the support library r13 or newer for these features.\",\n" +
            "\t\t\"fork\": false,\n" +
            "\t\t\"url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2\",\n" +
            "\t\t\"forks_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/forks\",\n" +
            "\t\t\"keys_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/keys{/key_id}\",\n" +
            "\t\t\"collaborators_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/collaborators{/collaborator}\",\n" +
            "\t\t\"teams_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/teams\",\n" +
            "\t\t\"hooks_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/hooks\",\n" +
            "\t\t\"issue_events_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/issues/events{/number}\",\n" +
            "\t\t\"events_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/events\",\n" +
            "\t\t\"assignees_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/assignees{/user}\",\n" +
            "\t\t\"branches_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/branches{/branch}\",\n" +
            "\t\t\"tags_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/tags\",\n" +
            "\t\t\"blobs_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/git/blobs{/sha}\",\n" +
            "\t\t\"git_tags_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/git/tags{/sha}\",\n" +
            "\t\t\"git_refs_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/git/refs{/sha}\",\n" +
            "\t\t\"trees_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/git/trees{/sha}\",\n" +
            "\t\t\"statuses_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/statuses/{sha}\",\n" +
            "\t\t\"languages_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/languages\",\n" +
            "\t\t\"stargazers_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/stargazers\",\n" +
            "\t\t\"contributors_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/contributors\",\n" +
            "\t\t\"subscribers_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/subscribers\",\n" +
            "\t\t\"subscription_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/subscription\",\n" +
            "\t\t\"commits_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/commits{/sha}\",\n" +
            "\t\t\"git_commits_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/git/commits{/sha}\",\n" +
            "\t\t\"comments_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/comments{/number}\",\n" +
            "\t\t\"issue_comment_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/issues/comments{/number}\",\n" +
            "\t\t\"contents_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/contents/{+path}\",\n" +
            "\t\t\"compare_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/compare/{base}...{head}\",\n" +
            "\t\t\"merges_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/merges\",\n" +
            "\t\t\"archive_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/{archive_format}{/ref}\",\n" +
            "\t\t\"downloads_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/downloads\",\n" +
            "\t\t\"issues_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/issues{/number}\",\n" +
            "\t\t\"pulls_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/pulls{/number}\",\n" +
            "\t\t\"milestones_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/milestones{/number}\",\n" +
            "\t\t\"notifications_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/notifications{?since,all,participating}\",\n" +
            "\t\t\"labels_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/labels{/name}\",\n" +
            "\t\t\"releases_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/releases{/id}\",\n" +
            "\t\t\"deployments_url\": \"https://api.github.com/repos/JakeWharton/ActivityCompat2/deployments\",\n" +
            "\t\t\"created_at\": \"2012-07-06T20:00:58Z\",\n" +
            "\t\t\"updated_at\": \"2017-09-09T22:06:30Z\",\n" +
            "\t\t\"pushed_at\": \"2013-05-27T00:22:28Z\",\n" +
            "\t\t\"git_url\": \"git://github.com/JakeWharton/ActivityCompat2.git\",\n" +
            "\t\t\"ssh_url\": \"git@github.com:JakeWharton/ActivityCompat2.git\",\n" +
            "\t\t\"clone_url\": \"https://github.com/JakeWharton/ActivityCompat2.git\",\n" +
            "\t\t\"svn_url\": \"https://github.com/JakeWharton/ActivityCompat2\",\n" +
            "\t\t\"homepage\": \"\",\n" +
            "\t\t\"size\": 433,\n" +
            "\t\t\"stargazers_count\": 79,\n" +
            "\t\t\"watchers_count\": 79,\n" +
            "\t\t\"language\": \"Java\",\n" +
            "\t\t\"has_issues\": false,\n" +
            "\t\t\"has_projects\": true,\n" +
            "\t\t\"has_downloads\": true,\n" +
            "\t\t\"has_wiki\": false,\n" +
            "\t\t\"has_pages\": false,\n" +
            "\t\t\"forks_count\": 11,\n" +
            "\t\t\"mirror_url\": null,\n" +
            "\t\t\"open_issues_count\": 0,\n" +
            "\t\t\"forks\": 11,\n" +
            "\t\t\"open_issues\": 0,\n" +
            "\t\t\"watchers\": 79,\n" +
            "\t\t\"default_branch\": \"master\"\n" +
            "\t}\n" +
            "]";

}
